services:
  # Servicio de Base de Datos
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SecretPassword123!
    ports:
      - "5432:5432" # Expuesto para inspección externa opcional (ej: DBeaver)
    volumes:
      - pgdata_vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Servicio de API .NET
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=appdb;Username=admin;Password=SecretPassword123!
    depends_on:
      - postgres_db
    networks:
      - app-network

volumes:
  pgdata_vol:

networks:
  app-network:
    driver: bridge
