services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
