FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o /app/publish
WORKDIR /app/publish
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "Plantilla_practica.dll"]
